fos_user_security_login:
    path:      /login/
    defaults:  { _controller: FOSUserBundle:Security:login, _method: GET|POST }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

    
app_front:
    resource: "@AppFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
